# Generated by Django 3.2.21 on 2023-11-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='posted',
            field=models.DateField(),
        ),
    ]
